/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Dashboard;

import Connector.Connector;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author macbook
 */
public class RatingPage extends javax.swing.JFrame {
    DefaultTableModel defaultTableModel;

    /**
     * Creates new form RatingPage
     */
    public RatingPage(MainPage mp) {
        initComponents();
                defaultTableModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        mp.setIsRatingShowing(true);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                // This code will be executed when the frame is closing
                System.out.println("Tat may");
                mp.setIsRatingShowing(false);
                dispose();
            }
        });
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTable1.setModel(defaultTableModel);
        getCinemaRates();
        getCinemaNames();
        setVisible(true);
        formPn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        cinemaNames = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        formPn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cnNameLb = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cinemaCbox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cinemaCm = new javax.swing.JTextArea();
        Submit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        cinemaNames.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cinema name" }));
        cinemaNames.setToolTipText("Movie names");
        cinemaNames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinemaNamesActionPerformed(evt);
            }
        });

        formPn.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("Cinema:");

        cnNameLb.setText("name");

        jLabel3.setText("Rating:");

        cinemaCbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        cinemaCbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinemaCboxActionPerformed(evt);
            }
        });

        jLabel4.setText("Comment:");

        cinemaCm.setColumns(20);
        cinemaCm.setRows(5);
        jScrollPane1.setViewportView(cinemaCm);

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formPnLayout = new javax.swing.GroupLayout(formPn);
        formPn.setLayout(formPnLayout);
        formPnLayout.setHorizontalGroup(
            formPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(formPnLayout.createSequentialGroup()
                        .addGroup(formPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formPnLayout.createSequentialGroup()
                                .addGroup(formPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGroup(formPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(formPnLayout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(cnNameLb))
                                    .addGroup(formPnLayout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(cinemaCbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(formPnLayout.createSequentialGroup()
                .addGap(362, 362, 362)
                .addComponent(Submit)
                .addContainerGap(392, Short.MAX_VALUE))
        );
        formPnLayout.setVerticalGroup(
            formPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cnNameLb))
                .addGap(9, 9, 9)
                .addGroup(formPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cinemaCbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Submit)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Average"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formPn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cinemaNames, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backBtn))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(cinemaNames, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formPn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void cinemaNamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinemaNamesActionPerformed
        // TODO add your handling code here:
        String selectedValue = cinemaNames.getSelectedItem().toString();
        if (!selectedValue.equals("Cinema name")) {
            formPn.setVisible(true);
            cnNameLb.setText(selectedValue);
        } else {
            formPn.setVisible(false);
        }
    }//GEN-LAST:event_cinemaNamesActionPerformed

    private void cinemaCboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinemaCboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cinemaCboxActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        String rating = cinemaCbox.getSelectedItem().toString();
        String cinemaName = cnNameLb.getText();
        String comment = cinemaCm.getText();
        try (Connection conn = Connector.getInstance().getConnection(); Statement stmt = conn.createStatement()) {
            String SQL = "INSERT INTO Review VALUES" +
                    "(" + cinemaName + ", " + comment + ", " + rating + ")";
            System.out.println(SQL);
            ResultSet rs = stmt.executeQuery(SQL);
            System.out.println("Insert user comment succeed!");
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_SubmitActionPerformed

    private void getCinemaRates() {
        String connectionUrl = "jdbc:sqlserver://sql.bsite.net\\MSSQL2016;encrypt=false;databaseName=giakhuong0703_Cinema;user=giakhuong0703_Cinema;password=khuong@07032003";
        try (Connection conn = DriverManager.getConnection(connectionUrl); Statement stmt = conn.createStatement()) {
            String SQL = "SELECT\n" +
                    "    cinemaName AS 'Name',\n" +
                    "    CAST(ROUND(CAST(SUM(ratePoint * num) AS FLOAT) / CAST(SUM(num) AS FLOAT), 2) AS DECIMAL(10, 2)) AS 'Average'\n" +
                    "FROM (\n" +
                    "    SELECT\n" +
                    "        r.cinemaId,\n" +
                    "        c.cinemaName,\n" +
                    "        r.ratePoint,\n" +
                    "        SUM(r.ratePoint) AS num\n" +
                    "    FROM\n" +
                    "        Review r\n" +
                    "    JOIN Cinemas c ON r.cinemaId = c.cinemaId\n" +
                    "    GROUP BY\n" +
                    "        r.cinemaId,\n" +
                    "        c.cinemaName,\n" +
                    "        r.ratePoint\n" +
                    ") AS subquery\n" +
                    "GROUP BY\n" +
                    "    cinemaName;";
            ResultSet rs = stmt.executeQuery(SQL);
            ResultSetMetaData metaData = rs.getMetaData();
            int numberOfColumns = metaData.getColumnCount();
            defaultTableModel.setRowCount(0);    // Clears rows
            defaultTableModel.setColumnCount(0); // Clears columns

            for (int i = 1; i <= numberOfColumns; i++) {
                defaultTableModel.addColumn(metaData.getColumnName(i));
            }

            Object[] rowData = new Object[numberOfColumns];

            while (rs.next()) {
                for (int i = 1; i <= numberOfColumns; i++) {
                    rowData[i - 1] = rs.getObject(i);
                }
                defaultTableModel.insertRow(0, rowData);
            }
            conn.close();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    
    private void getCinemaNames() {
        String connectionUrl = "jdbc:sqlserver://sql.bsite.net\\MSSQL2016;encrypt=false;databaseName=giakhuong0703_Cinema;user=giakhuong0703_Cinema;password=khuong@07032003";
        try (Connection conn = DriverManager.getConnection(connectionUrl); Statement stmt = conn.createStatement()) {
            String SQL = "SELECT DISTINCT C.cinemaName AS 'Cinema'" +
             "FROM Cinemas C ";
            ResultSet rs = stmt.executeQuery(SQL);
            StringBuilder results = new StringBuilder();
            ResultSetMetaData metaData = rs.getMetaData();
            int numberOfColumns = metaData.getColumnCount();
            while(rs.next()) {
                for (int i = 1; i <= numberOfColumns; i++) {
                    cinemaNames.addItem(rs.getObject(i).toString());
                }
            }
            conn.close();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RatingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RatingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RatingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RatingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Submit;
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox<String> cinemaCbox;
    private javax.swing.JTextArea cinemaCm;
    private javax.swing.JComboBox<String> cinemaNames;
    private javax.swing.JLabel cnNameLb;
    private javax.swing.JPanel formPn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
